import { BolaoData } from "./types";

export const DEFAULT_BOLAO_DATA: BolaoData = {
  pass: '123456',
  t1: 'BOLÃO',
  t2: 'DA COPA',
  badge: '100% via WhatsApp · Comunidade Exclusiva',
  eyebrow: 'Copa do Mundo 2026',
  sub: 'Participe do maior bolão da Copa direto pelo seu WhatsApp.<br><strong>Simples, seguro e cheio de prêmios.</strong>',
  ctah: 'Entrar na Comunidade',
  ctaf: 'Acessar a Comunidade',
  csub: 'Entre agora na comunidade e garanta sua vaga no bolão mais animado da Copa!',
  tr1: 'Pagamento seguro via Pix',
  tr2: 'Transparência total',
  tr3: 'Só precisa do WhatsApp',
  foot: '⚽ BOLÃO FC 2026 · Feito com ❤️ para a comunidade',
  lh: '#entrar',
  lf: '#entrar',
  wn: '🏆 BOLÃO FC 2026',
  ws: 'Comunidade · 128 participantes',
  s1n: '48',
  s1l: 'Jogos na fase de grupos',
  s2n: '100%',
  s2l: 'pelo WhatsApp',
  s3n: 'R$?',
  s3l: 'Em prêmios',
  s4n: '0',
  s4l: 'Apps pra baixar',
  st1t: 'Entre na Comunidade',
  st1d: 'Clique no link e entre na nossa comunidade exclusiva no WhatsApp. Rápido e sem burocracia.',
  st2t: 'Pague sua cota',
  st2d: 'Faça o pagamento via Pix da sua cota de participação. Simples e seguro.',
  st3t: 'Palpite nos jogos',
  st3d: 'Antes de cada rodada, envie seus palpites no grupo. Acerte o vencedor ou empate!',
  st4t: 'Ganhe os prêmios',
  st4d: 'Quem acertar o maior número de jogos leva o prêmio principal. Simples assim!',
  psub: 'O valor dos prêmios cresce com o número de participantes.',
  pnote: '* Os outros 30% cobrem custos de organização e operação do bolão.',
  p1v: '70%',
  p1d: 'do total arrecadado',
  rules: [
    'Ganha quem acertar todos os 8 jogos da rodada',
    'Se houver mais de um ganhador, o prêmio será dividido igualmente',
    'A prioridade é sempre de quem acertar o maior número de jogos (ex: 8 acertos)',
    'Se ninguém acertar 8, o prêmio vai para quem acertar 7, e assim por diante',
    'Palpites devem ser enviados até 15 min antes do jogo',
    'Pagamentos via Pix, rápido e seguro'
  ],
  isAuditReady: false,
  loginImg: 'https://picsum.photos/seed/football-20/1920/1080',
  loginBadge: 'O MAIOR BOLÃO DO BRASIL',
  loginTitle1: 'BOLÃO',
  loginTitle2: 'FC',
  loginSub: 'Sua chance de mostrar que entende de futebol e ganhar prêmios incríveis. Faça seus palpites agora!',
  deadline: '',
  isBettingClosed: false,
  isOverrideClosed: false,
  nextRoundTitle: 'Próxima Rodada',
  nextRoundDate: '',
  nextRoundTime: '',
  pixKey: '3c496ef8-44bd-4cc7-87b4-a2c950ca2e03',
  pricePerTicket: 10,
};

export const STORAGE_KEY = 'bolao_cfg_v1';
